# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-ast
  - id: check-docstring-first

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.1.0
  hooks:
  - id: add-trailing-comma

- repo: local
  hooks:
  - id: black
    name: Format with Black
    entry: poetry run black .
    language: system
    types: [python]

  - id: autoflake
    name: autoflake
    entry: poetry run autoflake
    language: system
    types: [python]
    args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

  - id: isort
    name: isort
    entry: poetry run isort
    language: system
    types: [python]

  - id: flake8
    name: Check with Flake8
    entry: poetry run flake8
    language: system
    pass_filenames: false
    types: [python]
    args: [--count, .]

  - id: mypy
    name: Validate types with MyPy
    entry: poetry run mypy
    language: system
    types: [python]
    pass_filenames: false
    args: [.]

  - id: pytest-check
    name: pytest-check
    entry: poetry run pytest .
    language: system
    pass_filenames: false
    always_run: true
