"""initial migrations

Revision ID: 54acd3f86904
Revises:
Create Date: 2022-12-04 18:33:41.865874

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "54acd3f86904"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_snap_items_item_id", table_name="snap_items")
    op.drop_table("snap_items")
    op.drop_index("ix_snaps_customer_id", table_name="snaps")
    op.drop_index("ix_snaps_id", table_name="snaps")
    op.drop_index("ix_snaps_store_id", table_name="snaps")
    op.drop_table("snaps")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "snaps",
        sa.Column(
            "last_modified",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "description",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "snap_url",
            sa.VARCHAR(length=150),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "store_id",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "customer_id",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="snaps_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_snaps_store_id", "snaps", ["store_id"], unique=False)
    op.create_index("ix_snaps_id", "snaps", ["id"], unique=False)
    op.create_index("ix_snaps_customer_id", "snaps", ["customer_id"], unique=False)
    op.create_table(
        "snap_items",
        sa.Column("id", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("item_id", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("snap_id", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["snap_id"],
            ["snaps.id"],
            name="snap_items_snap_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="snap_items_pkey"),
    )
    op.create_index("ix_snap_items_item_id", "snap_items", ["item_id"], unique=False)
    # ### end Alembic commands ###
