#main.yml
#This workflow will install Python dependencies, lint using Black, run tests using Pytest

name: snapshots-github-actions

on:
  push:

  pull_request:
    branches:
    - main

#A workflow job running sequentially
jobs:
  build:
    #runs-on: defines The workflow runner
    runs-on: ubuntu-latest
    #steps: defines a series of tasks executed by the Job
    steps:
    - uses: actions/checkout@v2
    - run: | # To fetch all history for all tags and branches
        git fetch --prune --unshallow

      #Task for setting up Python using actions/setup-python@v2 Github action
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

      #Task for installing dependencies, multi-line command
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black pytest
        if [ -f config/requirements/requirements.txt ]; then pip install -r config/requirements/requirements.txt; fi

    - name: Test using pytest
      run: |
        # Run automated tests using pytest
        pytest
